// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrrR5G0lWze7m_c4F5qGx0CMBo9QhwBgo',
    appId: '1:579904357106:web:0de5c152d04295ff98466b',
    messagingSenderId: '579904357106',
    projectId: 'myminsufirebase',
    authDomain: 'myminsufirebase.firebaseapp.com',
    storageBucket: 'myminsufirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR3szIwpzJ1XlY0c1_zeu6a4UPndKkCFo',
    appId: '1:579904357106:android:d8ae77befd1b3ffb98466b',
    messagingSenderId: '579904357106',
    projectId: 'myminsufirebase',
    storageBucket: 'myminsufirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk087jkxYeRWWOwDazQH6tL6orT_7QwWI',
    appId: '1:579904357106:ios:d6e099c036bd48a798466b',
    messagingSenderId: '579904357106',
    projectId: 'myminsufirebase',
    storageBucket: 'myminsufirebase.appspot.com',
    iosClientId:
        '579904357106-bpk1rvahcd7m5ledd5gv0v32o4mf3qbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk087jkxYeRWWOwDazQH6tL6orT_7QwWI',
    appId: '1:579904357106:ios:d6e099c036bd48a798466b',
    messagingSenderId: '579904357106',
    projectId: 'myminsufirebase',
    storageBucket: 'myminsufirebase.appspot.com',
    iosClientId:
        '579904357106-bpk1rvahcd7m5ledd5gv0v32o4mf3qbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
