// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6IFkRjA5Ca9z1rpU4Ey6lKq20LGOb8H4',
    appId: '1:483099337373:web:f7c19fc35135335d6daa74',
    messagingSenderId: '483099337373',
    projectId: 'studycat-ff601',
    authDomain: 'studycat-ff601.firebaseapp.com',
    storageBucket: 'studycat-ff601.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm2vuErI1lZVqsc2H1RX2OCwwUKt04RZc',
    appId: '1:483099337373:android:d3b938c164070ccb6daa74',
    messagingSenderId: '483099337373',
    projectId: 'studycat-ff601',
    storageBucket: 'studycat-ff601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeERlPBtydgscPFeOJImjhiKr_ELGfT2Q',
    appId: '1:483099337373:ios:f062e09aefa39c886daa74',
    messagingSenderId: '483099337373',
    projectId: 'studycat-ff601',
    storageBucket: 'studycat-ff601.appspot.com',
    iosClientId: '483099337373-ip9hf50lbr0s2gn7fclqpu28sa46u1l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.studycat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeERlPBtydgscPFeOJImjhiKr_ELGfT2Q',
    appId: '1:483099337373:ios:20969269e64737916daa74',
    messagingSenderId: '483099337373',
    projectId: 'studycat-ff601',
    storageBucket: 'studycat-ff601.appspot.com',
    iosClientId: '483099337373-hlvkvo6tdoljndcdhd7mgou8t55doglf.apps.googleusercontent.com',
    iosBundleId: 'com.example.studycat.RunnerTests',
  );
}
